### PR TITLE
upgrade to go1.9

### PR DESCRIPTION
**Pull request by tejasmanohar**
I just pushed this to a branch to play with for now. Can merge when we feel like it's more stable.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
@achille-roussel @abraithwaite Do you think we should merge this or wait? I'm indifferent / don't know enough about how past Go releases have gone to make a decision

**Comment by abraithwaite** [comment]
I'm indifferent.  I'm not sure where all it's used.

I will say that in the past, I've always updated day one and never had any issues (or regressions) resulting from that.

**Comment by achille-roussel** [comment]
In the past we've waited for the x.x.1 release before adopting a new version of Go, there had been a few critical bugs in x.x.0 versions.

The process we followed last time was to push a tag with the new version so we could start experimenting with it.

**Comment by achille-roussel** [comment]
I pushed an image with the 1.9 tag on docker hub => https://hub.docker.com/r/segment/golang/tags/

**Comment by achille-roussel** [comment]
Hey guys, I think it's more than time to make `latest` build with 1.9 (maybe even 1.9..3).

Any objections? Otherwise I'll move forward and make the change.

**Comment by abraithwaite** [comment]
Haha, I completely forgot about this.  We should definitely upgrade before 1.10 comes out!

**Comment by tejasmanohar** [comment]
Go for it

**Comment by abraithwaite** [comment]
Is this still relevant with the new circle setup?

**Comment by tejasmanohar** [comment]
Depends on your usage. I think it is for Personas'.

**Comment by achille-roussel** [comment]
I don’t see much needs for projects I’m involved with, this PR will probably die with the migration to circle enterprise

**Comment by achille-roussel** [comment]
Closing because this PR is outdated.

**Pull request closed without merging**
