### PR TITLE
1.8.0

### PR DESCRIPTION
**Pull request by achille-roussel**

### CODE REVIEW

**Comment by kevinburke** [comment]
I might hold off until 1.8.1 to be honest, there are some interesting errors in 1.8.0. Let me find the list.

**Comment by kevinburke** [comment]
https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3AGo1.8.1%20

**Comment by achille-roussel** [comment]
Interesting, I'm gonna do the wise thing and follow your advice.

**Comment by tysonmote** [comment]
We should probably have a policy of waiting for the x.x.1 release of any Go version. As incredible as Go's stability is, they have a little bit of a history of releasing the occasional obscure and difficult to debug bug in a new minor-level release. I've been bit by that a few times in the past. :(

**Comment by achille-roussel** [comment]
Sounds good to me 👍

**Pull request merged**
